version: '3.8'

services:
  main:
    image: main:latest
    container_name: main-container
    environment:
      - service.db.url=http://db:8082
    ports:
      - "8081:8081"
    networks:
      - mynetwork

  db:
    image: db:latest
    container_name: db-container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/iManager
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1411
    ports:
      - "8082:8082"
    networks:
      - mynetwork

  project-task:
    image: project-task:latest
    container_name: project-task-container
    environment:
      - service.db.url=http://db:8082
      - service.main.url=http://main:8081
    ports:
      - "8085:8085"
    networks:
      - mynetwork

  notification:
    image: notification:latest
    container_name: notification-container
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
